{\rtf1\ansi\ansicpg1252\cocoartf2821
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 version: '3.8'\
\
services:\
  postgres:\
    image: postgres:14\
    container_name: smartbank-db\
    restart: always\
    environment:\
      POSTGRES_USER: postgres\
      POSTGRES_PASSWORD: your_password_here\
      POSTGRES_DB: smartbank\
    ports:\
      - "5432:5432"\
    volumes:\
      - pg_data:/var/lib/postgresql/data\
\
  app:\
    build: .\
    container_name: smartbank-app\
    depends_on:\
      - postgres\
    ports:\
      - "8080:8080"\
    environment:\
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartbank\
      SPRING_DATASOURCE_USERNAME: postgres\
      SPRING_DATASOURCE_PASSWORD: your_password_here\
    networks:\
      - smartbank-net\
\
volumes:\
  pg_data:\
\
networks:\
  smartbank-net:\
}